# Centralized limits — mirrors markus/packages/shared/src/limits.ts pattern (simplified)

TASK_PAGE_SIZE = 20
TASK_GET_NOTES_DEFAULT = 50

NOTEBOOK_MAX_ENTRIES = 4
NOTEBOOK_MAX_CHARS = 2000
NOTEBOOK_MAX_CHARS_PER_ENTRY = 2000

HEARTBEAT_INTERVAL_MIN = 30
HEARTBEAT_JITTER_SEC = 60
MAILBOX_TIMEOUT_MIN = 10
MAILBOX_TTL_DAYS = 3
MAILBOX_COALESCE_MS = 200

SYSTEM_KNOWLEDGE_CHARS = 8000
SYSTEM_MY_TASKS_MAX = 15
PROMPT_KNOWLEDGE_TOKENS = 1500

TRIAGE_THRESHOLD = 2
TRIAGE_MAX_ITEMS = 50

SUBAGENT_MAX_PARALLEL = 10
SHELL_TIMEOUT_SEC = 60
SESSION_COMPACT_TOKENS = 2000

COMPLETION_MARKER = "<<HANDLE_COMPLETE>>"

GST_RATES = [5, 12, 18, 28]
INVOICE_SEQ_PAD = 4
ARCHIVE_AFTER_DAYS = 30
