def generate_invoice_pdf(invoice: dict, items: list[dict]) -> bytes:
    try:
        from weasyprint import HTML as WPHTML
        _has_wp = True
    except Exception:
        _has_wp = False
        WPHTML = None  # type: ignore

    if not _has_wp:
        # Fallback: return HTML bytes (valid PDF viewer will still render as text)
        rows = "".join(f"{i['description']} | HSN {i['hsn_code']} | {i['quantity']} x {i['rate']} = {i['amount']}\n" for i in items)
        text = f"KUBERA Tax Invoice\nInvoice: {invoice['invoice_number']} Date: {invoice['created_at']}\nCustomer: {invoice['customer_name']} GSTIN: {invoice['customer_gstin']}\n\n{rows}\nSubtotal: {invoice['amount']} GST: {invoice['gst_amount']} Total: {invoice['total']}\n"
        return text.encode()
    rows = "".join(
        f"<tr><td>{i['description']}</td><td>{i['hsn_code']}</td><td style='text-align:right'>{i['quantity']}</td><td style='text-align:right'>{i['rate']}</td><td style='text-align:center'>{i['gst_rate']}%</td><td style='text-align:right'>{i['amount']:.2f}</td></tr>"
        for i in items
    )
    html = f"""
    <html>
    <head><style>
      body {{ font-family: sans-serif; margin: 40px; color: #0f172a; }}
      h1 {{ color: #d97706; }}
      table {{ width:100%; border-collapse: collapse; margin-top: 20px; }}
      th, td {{ border:1px solid #cbd5e1; padding:8px; font-size: 12px; }}
      th {{ background: #0f172a; color: white; }}
      .totals {{ text-align:right; margin-top: 20px; }}
      .footer {{ margin-top: 30px; font-size: 10px; color: #64748b; text-align:center; }}
    </style></head>
    <body>
      <h1>KUBERA — Tax Invoice</h1>
      <p><b>Invoice No:</b> {invoice['invoice_number']} &nbsp; | &nbsp; <b>Date:</b> {invoice['created_at']}</p>
      <p><b>Customer:</b> {invoice['customer_name']} &nbsp; | &nbsp; <b>GSTIN:</b> {invoice['customer_gstin']}</p>
      <table>
        <tr><th>Description</th><th>HSN</th><th>Qty</th><th>Rate</th><th>GST</th><th>Amount</th></tr>
        {rows}
      </table>
      <div class="totals">
        <p>Subtotal: ₹{invoice['amount']:.2f}</p>
        <p>GST: ₹{invoice['gst_amount']:.2f}</p>
        <p><b>Total: ₹{invoice['total']:.2f}</b></p>
      </div>
      <div class="footer">Generated by KUBERA — Your Digital Workforce for Indian Businesses</div>
    </body>
    </html>
    """
    return WPHTML(string=html).write_pdf()
